apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: peoplelist
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/miketineo/peoplelist
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include manifests
    !/k8s-manifests/

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: peoplelist
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: peoplelist
  targetNamespace: peoplelist
